runtime: python27
api_version: 1
threadsafe: yes

#env_variables:
 # API_KEY: <API key for projects app engine>

handlers:

  - url: /
    static_files: src/index.html
    upload: src/index.html
  - url: /
    static_dir: src

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE